/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreatsRouteImport } from './routes/threats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'

const ThreatsRoute = ThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/logs': typeof LogsRoute
  '/policies': typeof PoliciesRoute
  '/settings': typeof SettingsRoute
  '/threats': typeof ThreatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/logs': typeof LogsRoute
  '/policies': typeof PoliciesRoute
  '/settings': typeof SettingsRoute
  '/threats': typeof ThreatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/logs': typeof LogsRoute
  '/policies': typeof PoliciesRoute
  '/settings': typeof SettingsRoute
  '/threats': typeof ThreatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agents' | '/logs' | '/policies' | '/settings' | '/threats'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agents' | '/logs' | '/policies' | '/settings' | '/threats'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/logs'
    | '/policies'
    | '/settings'
    | '/threats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  LogsRoute: typeof LogsRoute
  PoliciesRoute: typeof PoliciesRoute
  SettingsRoute: typeof SettingsRoute
  ThreatsRoute: typeof ThreatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threats': {
      id: '/threats'
      path: '/threats'
      fullPath: '/threats'
      preLoaderRoute: typeof ThreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  LogsRoute: LogsRoute,
  PoliciesRoute: PoliciesRoute,
  SettingsRoute: SettingsRoute,
  ThreatsRoute: ThreatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
